theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jemoji

relative_links:
  enabled: true
  collections: true

title: "Octi"
description: "A multi-device manager for Android"
author: "by Matthias Urhahn"

include:
  - PRIVACY_POLICY.md
exclude:
  - buildSrc
  - gradle/wrapper
  - fastlane
  - Gemfile
  - Gemfile.lock
  - crowdin*
  - app
  - app-common-test
  - app-common
  - module-core
  - modules-clipboard
  - modules-meta
  - modules-power
  - modules-wifi
  - sync-core
  - syncs-gdrive
  - syncs-kserver
