theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jemoji

relative_links:
  enabled: true
  collections: true

title: "Octi - Multi-Device Sync"
description: "See battery, WiFi, clipboard and files across all your Android devices"
author: "by Matthias Urhahn"

include:
  - PRIVACY_POLICY.md
  - CHANGELOG.md
exclude:
  - README.md
  - branding
  - buildSrc
  - gradle/wrapper
  - fastlane
  - crowdin*
  - app
  - app-common-test
  - app-common
  - module-core
  - modules-apps
  - modules-clipboard
  - modules-connectivity
  - modules-files
  - modules-meta
  - modules-power
  - modules-wifi
  - sync-core
  - syncs-gdrive
  - syncs-octiserver
  - CONTRIBUTING.md
