"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"project_id": "741615"
"preserve_hierarchy": true

"files": [
  {
    "source": "/app-common/src/main/res/values/strings.xml",
    "dest": "/strings-common.xml",
    "translation": "/app-common/src/main/res/values-%android_code%/strings.xml",
    #    "update_option" : "update_without_changes",
    "languages_mapping": &stringmapping {
      "android_code": {
        "sc": "sc-rIT",
        "sq": "sq-rAL",
        "ar": "ar",
        "am": "am",
        "hy-AM": "hy-rAM",
        "az": "az",
        "be": "be",
        "bn": "bn-rBD",
        "bg": "bg",
        "ca": "ca",
        "cs": "cs",
        "da": "da",
        "de": "de",
        "el": "el",
        "es-ES": "es",
        "es-AR": "es-rAR",
        "es-MX": "es-rMX",
        "es-VE": "es-rVE",
        "et": "et-rEE",
        "eu": "eu-rES",
        "fa": "fa",
        "fil": "fil",
        "fi": "fi",
        "fr": "fr",
        "gl": "gl-rES",
        "hr": "hr",
        "hu": "hu",
        "is": "is",
        "id": "in",
        "it": "it",
        "he": "iw",
        "ja": "ja",
        "ka": "ka-rGE",
        "km": "km-rKH",
        "kn": "kn-rIN",
        "ko": "ko",
        "ky": "ky-rKG",
        "lt": "lt",
        "lv": "lv",
        "lo": "lo-rLA",
        "ms": "ms",
        "ml-IN": "ml-rIN",
        "mn": "mn-rMN",
        "mr": "mr-rIN",
        "my": "my-rMM",
        "ne-NP": "ne-rNP",
        "nl": "nl",
        "nb": "nb",
        "pl": "pl",
        "pt-PT": "pt",
        "pt-BR": "pt-rBR",
        "ro": "ro",
        "ru": "ru",
        "rm-CH": "rm",
        "si-LK": "si-rLK",
        "sk": "sk",
        "sl": "sl",
        "sr": "sr",
        "sv-SE": "sv",
        "sw": "sw",
        "th": "th",
        "ta": "ta-rIN",
        "te": "te-rIN",
        "tr": "tr",
        "uk": "uk",
        "ur-IN": "ur-rIN",
        "uz": "uz",
        "vi": "vi",
        "zh-CN": "zh-rCN",
        "zh-HK": "zh-rHK",
        "zh-TW": "zh-rTW",
        "zu": "zu"
      }
    }
  }, {
    "source": "/app/src/gplay/res/values/strings.xml",
    "dest": "/strings-app-gplay.xml",
    "translation": "/app/src/gplay/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/app/src/foss/res/values/strings.xml",
    "dest": "/strings-app-foss.xml",
    "translation": "/app/src/foss/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/app/src/main/res/values/strings.xml",
    "dest": "/strings-app.xml",
    "translation": "/app/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/module-core/src/main/res/values/strings.xml",
    "dest": "/strings-module-core.xml",
    "translation": "/module-core/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/modules-apps/src/main/res/values/strings.xml",
    "dest": "/strings-modules-apps.xml",
    "translation": "/modules-apps/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/modules-clipboard/src/main/res/values/strings.xml",
    "dest": "/strings-modules-clipboard.xml",
    "translation": "/modules-clipboard/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/modules-meta/src/main/res/values/strings.xml",
    "dest": "/strings-modules-meta.xml",
    "translation": "/modules-meta/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/modules-power/src/main/res/values/strings.xml",
    "dest": "/strings-modules-power.xml",
    "translation": "/modules-power/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/modules-wifi/src/main/res/values/strings.xml",
    "dest": "/strings-modules-wifi.xml",
    "translation": "/modules-wifi/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/sync-core/src/main/res/values/strings.xml",
    "dest": "/strings-sync-core.xml",
    "translation": "/sync-core/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/syncs-gdrive/src/main/res/values/strings.xml",
    "dest": "/strings-syncs-gdrive.xml",
    "translation": "/syncs-gdrive/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/syncs-kserver/src/main/res/values/strings.xml",
    "dest": "/strings-syncs-kserver.xml",
    "translation": "/syncs-kserver/src/main/res/values-%android_code%/strings.xml",
    "languages_mapping": *stringmapping
  }, {
    "source": "/fastlane/metadata/android/en-US/full_description.txt",
    "dest": "/description.txt",
    "translation": "/fastlane/metadata/android/%locale%/full_description.txt",
    "languages_mapping": &playstoremapping {
      "locale": {
        "af": "af",
        "ar": "ar",
        "am": "am",
        "az": "az-AZ",
        "be": "be",
        "bn": "bn-BD",
        "bg": "bg",
        "ca": "ca",
        "cs": "cs-CZ",
        "da": "da-DK",
        "de": "de-DE",
        "el": "el-GR",
        "es-ES": "es-ES",
        "es-AR": "es-AR",
        "es-MX": "es-419",
        "es-VE": "es-VE",
        "et": "et",
        "eu": "eu-ES",
        "fa": "fa",
        "fil": "fil",
        "fi": "fi-FI",
        "fr": "fr-FR",
        "fr-CA": "fr-CA",
        "gl": "gl-ES",
        "hr": "hr",
        "hu": "hu-HU",
        "hy-AM": "hy-AM",
        "is": "is-IS",
        "id": "id",
        "it": "it-IT",
        "he": "iw-IL",
        "hi": "hi-IN",
        "ja": "ja-JP",
        "ka": "ka-GE",
        "km": "km-KH",
        "kn": "kn-IN",
        "ko": "ko-KR",
        "ky": "ky-KG",
        "lt": "lt",
        "lv": "lv",
        "lo": "lo-LA",
        "mk": "mk-MK",
        "ms": "ms",
        "ml-IN": "ml-IN",
        "mn": "mn-MN",
        "mr": "mr-IN",
        "my": "my-MM",
        "ne-NP": "ne-NP",
        "nl": "nl-NL",
        "nb": "no-NO",
        "pl": "pl-PL",
        "pt-PT": "pt-PT",
        "pt-BR": "pt-BR",
        "ro": "ro",
        "ru": "ru-RU",
        "rm-CH": "rm",
        "si-LK": "si-LK",
        "sk": "sk",
        "sl": "sl",
        "sr": "sr",
        "sv-SE": "sv-SE",
        "sw": "sw",
        "th": "th",
        "ta": "ta-IN",
        "te": "te-IN",
        "tr": "tr-TR",
        "uk": "uk",
        "ur-IN": "ur-IN",
        "uz": "uz",
        "vi": "vi",
        "zh-CN": "zh-CN",
        "zh-HK": "zh-HK",
        "zh-TW": "zh-TW",
        "zu": "zu"
      }
    }
  }, {
    "source": "/fastlane/metadata/android/en-US/title.txt",
    "dest": "/title.txt",
    "translation": "/fastlane/metadata/android/%locale%/title.txt",
    "languages_mapping": *playstoremapping
  }, {
    "source": "/fastlane/metadata/android/en-US/short_description.txt",
    "dest": "/short_description.txt",
    "translation": "/fastlane/metadata/android/%locale%/short_description.txt",
    "languages_mapping": *playstoremapping
  }
]
