package eu.darken.octi.sync.core.interop

import eu.darken.octi.common.collections.toGzip
import eu.darken.octi.sync.core.blob.StreamingPayloadCipher
import eu.darken.octi.sync.core.encryption.PayloadEncryption
import okio.Buffer
import okio.ByteString
import okio.ByteString.Companion.decodeBase64
import okio.ByteString.Companion.encodeUtf8
import okio.ByteString.Companion.toByteString
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.condition.EnabledIfSystemProperty
import testhelpers.BaseTest
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import kotlin.io.path.exists
import kotlin.io.path.readBytes
import kotlin.io.path.writeBytes

/**
 * Opt-in fixture writer. Runs only when `-DgenerateInteropFixtures=true` is passed,
 * which is exactly what `./gradlew :sync-core:generateInteropFixtures` (the wrapper
 * task — see sync-core/build.gradle.kts) sets.
 *
 * Writes:
 *  - `sync-core/src/test/resources/interop/tink-vectors.json`
 *  - `sync-core/src/test/resources/interop/streaming-vectors.json`
 *  - `sync-core/src/test/resources/interop/manifest.json` (sha256 over the above)
 *
 * **Keyset stability.** If a fixture file already exists, the generator preserves
 * its committed keyset (parses out `keysetBase64`, reuses). Only ciphertext bytes
 * change between runs (random GCM-SIV nonces — see [InteropFixtures]). To rotate
 * the keyset, delete the file and re-run.
 *
 * **Output path.** Gradle sets `user.dir` to the project that owns the test —
 * here, `<root>/sync-core/`. We just write to `src/test/resources/interop/`.
 */
class InteropFixtureGeneratorTest : BaseTest() {

    private val payloadVectors = listOf(
        SourceVector("empty", ByteString.EMPTY, "device-a:module-x"),
        SourceVector("hello-world", "Hello, Octi!".encodeUtf8(), "device-a:module-x"),
        SourceVector(
            "with-special-chars",
            "device👋label".encodeUtf8(),
            "browser-1234:eu.darken.octi.module.core.clipboard",
        ),
        // Deterministic byte pattern: byte i = ((i * 31 + 17) and 0xff). Kotlin's
        // Random.nextBytes is not part of the language spec, so seeded output can
        // shift across Kotlin upgrades — bad for a committed contract.
        SourceVector(
            "approx-10kb",
            deterministicBytes(10_000).toByteString(),
            "device-b:eu.darken.octi.module.files",
        ),
    )

    // Sequential pattern: byte i = (i and 0xFF). Used for large vectors so we don't
    // commit megabytes of base64 plaintext to git (the plaintext is fully reconstructible
    // from kind+size; only the random-nonce ciphertext is non-deterministic).
    // Size 1 MiB + 1 is comfortably past Tink's 1 MB segment boundary; the exact
    // first-segment plaintext capacity (~1,048,553) would be more "minimal" but is
    // brittle to encode — leave that as a follow-up vector if a real Tink upgrade
    // ever shifts the layout.
    private val twoSegmentsPattern = StreamingPlaintextPattern(kind = "sequential", size = 1_048_577)

    private val streamingVectors = listOf(
        StreamingSource.Inline("empty", "device-a:module-x:key-1", ByteArray(0)),
        StreamingSource.Inline(
            "short",
            "device-a:module-x:key-2",
            "Hi from Octi blobs".toByteArray(Charsets.UTF_8),
        ),
        StreamingSource.Pattern(
            "two-segments",
            "device-b:eu.darken.octi.module.core.files:key-4",
            twoSegmentsPattern,
        ),
    )

    private fun deterministicBytes(size: Int): ByteArray =
        ByteArray(size) { i -> ((i * 31 + 17) and 0xff).toByte() }

    @Test
    @EnabledIfSystemProperty(named = "generateInteropFixtures", matches = "true")
    fun `regenerate cross-repo interop fixtures`() {
        val outDir = resolveOutputDir()
        Files.createDirectories(outDir)

        val tinkPath = outDir.resolve(InteropFixtures.TINK_FILE)
        val streamingPath = outDir.resolve(InteropFixtures.STREAMING_FILE)
        val manifestPath = outDir.resolve(InteropFixtures.MANIFEST_FILE)

        val (gcmsivCrypti, sivCrypti) = preparePayloadCrypti(tinkPath)
        val (streamingCipher, streamingKeyset) = prepareStreamingCipher(streamingPath)

        val tinkFixture = TinkVectorsFixture(
            schemaVersion = InteropFixtures.SCHEMA_VERSION,
            note = "Generated by InteropFixtureGeneratorTest. " +
                "Re-export with `./gradlew :sync-core:generateInteropFixtures`. " +
                "GCM-SIV is non-deterministic; expect ciphertext bytes to change every run.",
            gcmsiv = buildPayloadBlock(gcmsivCrypti, includeAad = true),
            siv = buildPayloadBlock(sivCrypti, includeAad = false),
        )

        val streamingFixture = buildStreamingFixture(streamingCipher, streamingKeyset)

        val tinkBytes = encode(tinkFixture, TinkVectorsFixture.serializer())
        val streamingBytes = encode(streamingFixture, StreamingVectorsFixture.serializer())

        tinkPath.writeBytes(tinkBytes)
        streamingPath.writeBytes(streamingBytes)

        val manifest = FixtureManifest(
            schemaVersion = InteropFixtures.SCHEMA_VERSION,
            source = "d4rken-org/octi",
            generator = "sync-core InteropFixtureGeneratorTest",
            files = sortedMapOf(
                InteropFixtures.TINK_FILE to FileEntry(InteropFixtures.sha256Hex(tinkBytes)),
                InteropFixtures.STREAMING_FILE to FileEntry(InteropFixtures.sha256Hex(streamingBytes)),
            ),
        )
        manifestPath.writeBytes(encode(manifest, FixtureManifest.serializer()))

        println("Wrote interop fixtures to $outDir")
    }

    private fun preparePayloadCrypti(existingTink: Path): Pair<PayloadEncryption, PayloadEncryption> {
        if (!existingTink.exists()) {
            return PayloadEncryption() to PayloadEncryption(useLegacyEncryption = true)
        }
        val existing = InteropFixtures.json.decodeFromString(
            TinkVectorsFixture.serializer(),
            existingTink.readBytes().toString(Charsets.UTF_8),
        )
        val gcmsiv = PayloadEncryption(
            keySet = PayloadEncryption.KeySet(
                type = existing.gcmsiv.keysetType,
                key = decodeBase64Required(existing.gcmsiv.keysetBase64),
            ),
        )
        val siv = PayloadEncryption(
            keySet = PayloadEncryption.KeySet(
                type = existing.siv.keysetType,
                key = decodeBase64Required(existing.siv.keysetBase64),
            ),
        )
        return gcmsiv to siv
    }

    private fun prepareStreamingCipher(existingStreaming: Path): Pair<StreamingPayloadCipher, PayloadEncryption.KeySet> {
        val keyset = if (existingStreaming.exists()) {
            val existing = InteropFixtures.json.decodeFromString(
                StreamingVectorsFixture.serializer(),
                existingStreaming.readBytes().toString(Charsets.UTF_8),
            )
            PayloadEncryption.KeySet(
                type = existing.keysetType,
                key = decodeBase64Required(existing.keysetBase64),
            )
        } else {
            PayloadEncryption().exportKeyset()
        }
        return StreamingPayloadCipher(keyset) to keyset
    }

    private fun buildPayloadBlock(crypti: PayloadEncryption, includeAad: Boolean): KeysetBlock {
        val keyset = crypti.exportKeyset()
        val vectors = payloadVectors.map { v ->
            // Legacy SIV ignores AAD by construction. The committed schema reflects that
            // by storing "" — populating a value we'd ignore would be misleading contract data.
            val aadString = if (includeAad) v.ad else ""
            val aadBytes = aadString.toByteArray(Charsets.UTF_8)
            val ciphertext = crypti.encrypt(v.plaintext.toGzip(), aadBytes)
            PayloadVector(
                name = v.name,
                plaintextBase64 = v.plaintext.base64(),
                aad = aadString,
                ciphertextBase64 = ciphertext.base64(),
            )
        }
        return KeysetBlock(
            keysetType = keyset.type,
            keysetBase64 = keyset.key.base64(),
            vectors = vectors,
        )
    }

    private fun buildStreamingFixture(
        cipher: StreamingPayloadCipher,
        keyset: PayloadEncryption.KeySet,
    ): StreamingVectorsFixture {
        val vectors = streamingVectors.map { v ->
            val plaintextBytes = v.materialize()
            val ct = Buffer()
            cipher.encrypt(Buffer().write(plaintextBytes), ct, v.aad.toByteArray(Charsets.UTF_8))
            val ctBytes = ct.readByteArray()
            StreamingVector(
                name = v.name,
                aad = v.aad,
                plaintextBase64 = if (v is StreamingSource.Inline) plaintextBytes.toByteString().base64() else null,
                plaintextPattern = if (v is StreamingSource.Pattern) v.pattern else null,
                plaintextSize = plaintextBytes.size,
                ciphertextBase64 = ctBytes.toByteString().base64(),
                ciphertextSize = ctBytes.size,
            )
        }
        return StreamingVectorsFixture(
            schemaVersion = InteropFixtures.SCHEMA_VERSION,
            note = "Generated by InteropFixtureGeneratorTest. " +
                "Re-export with `./gradlew :sync-core:generateInteropFixtures`. " +
                "Tink streaming AEAD is non-deterministic; expect ciphertext bytes to change every run.",
            keysetType = keyset.type,
            keysetBase64 = keyset.key.base64(),
            vectors = vectors,
        )
    }

    private fun <T> encode(value: T, serializer: kotlinx.serialization.KSerializer<T>): ByteArray =
        (InteropFixtures.json.encodeToString(serializer, value) + "\n").toByteArray(Charsets.UTF_8)

    private fun decodeBase64Required(s: String): ByteString =
        s.decodeBase64() ?: error("invalid base64 in committed fixture keyset")

    private fun resolveOutputDir(): Path {
        // The Gradle wrapper task `:sync-core:generateInteropFixtures` passes the exact
        // output directory via this system property. We refuse to guess from user.dir
        // because that's brittle across IDEs, composite builds, and Gradle changes.
        val configured = System.getProperty("interopFixturesOutDir")
            ?: error(
                "interopFixturesOutDir not set. Run via `./gradlew :sync-core:generateInteropFixtures` " +
                    "(which sets it), not directly via the test task.",
            )
        return Paths.get(configured).toAbsolutePath()
    }

    private data class SourceVector(val name: String, val plaintext: ByteString, val ad: String)

    private sealed class StreamingSource {
        abstract val name: String
        abstract val aad: String
        abstract fun materialize(): ByteArray

        data class Inline(
            override val name: String,
            override val aad: String,
            val plaintext: ByteArray,
        ) : StreamingSource() {
            override fun materialize() = plaintext
        }

        data class Pattern(
            override val name: String,
            override val aad: String,
            val pattern: StreamingPlaintextPattern,
        ) : StreamingSource() {
            override fun materialize() = InteropFixtures.materializePattern(pattern)
        }
    }
}
