package eu.darken.octi.sync.core.encryption

import eu.darken.octi.common.collections.fromGzip
import eu.darken.octi.common.collections.toByteString
import eu.darken.octi.common.collections.toGzip
import io.kotest.matchers.shouldBe
import okio.ByteString
import okio.ByteString.Companion.toByteString as bytesToByteString
import org.junit.jupiter.api.Test
import testhelpers.BaseTest
import java.nio.file.Paths
import kotlin.io.path.exists
import kotlin.io.path.writeText
import kotlin.random.Random

/**
 * Cross-language correctness pin between the Android client's [PayloadEncryption]
 * and the browser client's TypeScript equivalent in `octi-web/`.
 *
 * The TS code reimplements: Tink AES-256-GCM-SIV keyset proto parsing, AEAD with
 * the 5-byte `0x01 || keyId(4 BE)` Tink wire prefix, AD construction (`"<deviceId>:<moduleId>"`),
 * and the outer `gzip → encrypt / decrypt → gunzip` wrap that [OctiServerConnector]
 * applies. Any drift in any layer corrupts data silently — hence the golden vectors.
 *
 * **Always-on regression**: validates JVM-side roundtrip on every `./gradlew test`.
 *
 * **On-demand fixture export**: pass `-DgenerateTinkFixture=true` to write the
 * generated keyset + vectors to `octi-web/src/crypto/__fixtures__/tink-vectors.json`.
 * Commit the resulting file so the TS golden tests have stable input until the next
 * regeneration. GCM-SIV is non-deterministic (random nonce per encrypt), so the file
 * changes each export — re-generate only when intentionally rotating fixtures.
 */
class TinkVectorsExportTest : BaseTest() {

    private data class Vector(
        val name: String,
        val plaintext: ByteString,
        val ad: String,
    )

    private val vectors = listOf(
        Vector("empty", ByteString.EMPTY, "device-a:module-x"),
        Vector("hello-world", "Hello, Octi!".toByteString(), "device-a:module-x"),
        Vector("with-special-chars", "device👋label".toByteString(), "browser-1234:eu.darken.octi.module.core.clipboard"),
        Vector(
            "approx-10kb",
            Random(12345).nextBytes(10_000).bytesToByteString(),
            "device-b:eu.darken.octi.module.files",
        ),
    )

    @Test
    fun `JVM round-trip - gcmsiv with outer gzip wrap matches OctiServerConnector flow`() {
        val crypti = PayloadEncryption()
        for (v in vectors) {
            val encrypted = crypti.encrypt(v.plaintext.toGzip(), v.ad.toByteArray(Charsets.UTF_8))
            val decrypted = crypti.decrypt(encrypted, v.ad.toByteArray(Charsets.UTF_8)).fromGzip()
            decrypted shouldBe v.plaintext
        }
    }

    @Test
    fun `JVM round-trip - legacy siv ignores AD per PayloadEncryption contract`() {
        val crypti = PayloadEncryption(useLegacyEncryption = true)
        for (v in vectors) {
            val encrypted = crypti.encrypt(v.plaintext.toGzip())
            crypti.decrypt(encrypted).fromGzip() shouldBe v.plaintext
        }
    }

    @Test
    fun `export fixture to octi-web - opt-in via -DgenerateTinkFixture=true`() {
        // Default: assert the test is wired correctly without polluting another project.
        if (System.getProperty("generateTinkFixture") != "true") {
            return
        }

        val cryptiGcmSiv = PayloadEncryption()
        val cryptiSiv = PayloadEncryption(useLegacyEncryption = true)

        val fixture = buildString {
            append("{\n")
            append("  \"generatedAt\": \"")
            append(java.time.Instant.now().toString())
            append("\",\n")
            append("  \"note\": \"Generated by TinkVectorsExportTest; do not edit by hand. Re-export with `./gradlew :sync-core:testDebugUnitTest --tests *TinkVectorsExportTest* -DgenerateTinkFixture=true`.\",\n")
            appendKeysetBlock("gcmsiv", cryptiGcmSiv, includeAd = true)
            append(",\n")
            appendKeysetBlock("siv", cryptiSiv, includeAd = false)
            append("\n}\n")
        }

        // Gradle sets user.dir to the project root that owns the test (here, app-main).
        // Walk up looking for the sibling octi-web/ rather than hardcoding `..` depth —
        // works whether invoked from app-main/ or the octi/ super-root.
        var cursor: java.nio.file.Path? = Paths.get(System.getProperty("user.dir")).toAbsolutePath()
        var fixtureDir: java.nio.file.Path? = null
        while (cursor != null) {
            val candidate = cursor.resolve("octi-web").resolve("src").resolve("crypto").resolve("__fixtures__")
            if (candidate.exists()) {
                fixtureDir = candidate
                break
            }
            cursor = cursor.parent
        }
        checkNotNull(fixtureDir) {
            "Could not locate octi-web/src/crypto/__fixtures__ walking up from ${System.getProperty("user.dir")}; create the dir first"
        }
        val outPath = fixtureDir.resolve("tink-vectors.json")
        outPath.writeText(fixture)
        println("Wrote Tink fixture to $outPath")
    }

    private fun StringBuilder.appendKeysetBlock(
        name: String,
        crypti: PayloadEncryption,
        includeAd: Boolean,
    ) {
        val keyset = crypti.exportKeyset()
        append("  \"$name\": {\n")
        append("    \"keysetType\": \"${keyset.type}\",\n")
        append("    \"keysetBase64\": \"${keyset.key.base64()}\",\n")
        append("    \"vectors\": [\n")
        vectors.forEachIndexed { i, v ->
            val ad = if (includeAd) v.ad.toByteArray(Charsets.UTF_8) else ByteArray(0)
            // Wire layering must match OctiServerConnector.kt:586 / :501.
            val ciphertext = crypti.encrypt(v.plaintext.toGzip(), ad)
            append("      {\n")
            append("        \"name\": \"${v.name}\",\n")
            append("        \"plaintextBase64\": \"${v.plaintext.base64()}\",\n")
            // ad is the UTF-8 string; for SIV the TS side ignores it.
            append("        \"ad\": \"${escape(v.ad)}\",\n")
            append("        \"ciphertextBase64\": \"${ciphertext.base64()}\"\n")
            append("      }")
            if (i != vectors.lastIndex) append(",")
            append("\n")
        }
        append("    ]\n")
        append("  }")
    }

    private fun escape(s: String): String = s
        .replace("\\", "\\\\")
        .replace("\"", "\\\"")
}
