package eu.darken.octi.sync.core.blob

import eu.darken.octi.sync.core.encryption.PayloadEncryption
import io.kotest.matchers.shouldBe
import okio.Buffer
import okio.ByteString.Companion.toByteString
import org.junit.jupiter.api.Test
import testhelpers.BaseTest
import java.nio.file.Paths
import kotlin.io.path.exists
import kotlin.io.path.writeText
import kotlin.random.Random

/**
 * Cross-language correctness pin between Android's [StreamingPayloadCipher] and the
 * browser client's TypeScript re-implementation in `octi-web/src/crypto/`.
 *
 * Octi blobs are encrypted with Tink's `AesGcmHkdfStreaming` over a per-account key
 * derived via HKDF-SHA256 (`salt="octi-blob"`, `info="octi-blob-stream-v1"`). The TS
 * side must reproduce the entire stack: HKDF, per-segment AES-GCM with positional
 * nonces, and Tink's streaming wire framing. Drift in any layer corrupts data
 * silently — so we ship pinned vectors the TS golden tests round-trip against.
 *
 * **Always-on regression**: validates the JVM-side roundtrip on every `./gradlew test`.
 *
 * **On-demand fixture export**: pass `-DgenerateTinkFixture=true` to write the JSON
 * fixture to `octi-web/src/crypto/__fixtures__/streaming-vectors.json`. Same gradle
 * gate as TinkVectorsExportTest — already wired through sync-core/build.gradle.kts.
 */
class StreamingCipherVectorsExportTest : BaseTest() {

    private data class Vector(
        val name: String,
        val aad: String,
        val plaintext: ByteArray,
    )

    private val vectors = listOf(
        Vector("empty", "device-a:module-x:key-1", ByteArray(0)),
        Vector("short", "device-a:module-x:key-2", "Hi from Octi blobs".toByteArray(Charsets.UTF_8)),
        Vector("one-segment", "device-b:eu.darken.octi.module.core.files:key-3", Random(42).nextBytes(800_000)),
        // Crosses Tink's 1 MB segment boundary — exercises the multi-segment encode path.
        Vector("two-segments", "device-b:eu.darken.octi.module.core.files:key-4", Random(7).nextBytes(2_500_000)),
    )

    @Test
    fun `JVM round-trip - streaming cipher encrypts and decrypts`() {
        val keyset = PayloadEncryption().exportKeyset()
        val cipher = StreamingPayloadCipher(keyset)
        for (v in vectors) {
            val ct = Buffer()
            cipher.encrypt(Buffer().write(v.plaintext), ct, v.aad.toByteArray(Charsets.UTF_8))
            val pt = Buffer()
            cipher.decrypt(Buffer().write(ct.readByteArray()), pt, v.aad.toByteArray(Charsets.UTF_8))
            pt.readByteArray().toByteString() shouldBe v.plaintext.toByteString()
        }
    }

    @Test
    fun `export streaming fixture to octi-web - opt-in via -DgenerateTinkFixture=true`() {
        if (System.getProperty("generateTinkFixture") != "true") return

        val keyset = PayloadEncryption().exportKeyset()
        val cipher = StreamingPayloadCipher(keyset)

        val fixture = buildString {
            append("{\n")
            append("  \"generatedAt\": \"")
            append(java.time.Instant.now().toString())
            append("\",\n")
            append("  \"note\": \"Generated by StreamingCipherVectorsExportTest; do not edit by hand. Re-export with `./gradlew :sync-core:testDebugUnitTest --tests *StreamingCipherVectorsExportTest* -DgenerateTinkFixture=true`.\",\n")
            append("  \"keysetType\": \"${keyset.type}\",\n")
            append("  \"keysetBase64\": \"${keyset.key.base64()}\",\n")
            append("  \"vectors\": [\n")
            vectors.forEachIndexed { i, v ->
                val ct = Buffer()
                cipher.encrypt(Buffer().write(v.plaintext), ct, v.aad.toByteArray(Charsets.UTF_8))
                val ctBytes = ct.readByteArray().toByteString()
                append("    {\n")
                append("      \"name\": \"${v.name}\",\n")
                append("      \"aad\": \"${escape(v.aad)}\",\n")
                append("      \"plaintextBase64\": \"${v.plaintext.toByteString().base64()}\",\n")
                append("      \"plaintextSize\": ${v.plaintext.size},\n")
                append("      \"ciphertextBase64\": \"${ctBytes.base64()}\",\n")
                append("      \"ciphertextSize\": ${ctBytes.size}\n")
                append("    }")
                if (i != vectors.lastIndex) append(",")
                append("\n")
            }
            append("  ]\n")
            append("}\n")
        }

        // Path resolution mirrors TinkVectorsExportTest — walk up looking for the
        // sibling octi-web/ rather than hardcoding `..` depth.
        var cursor: java.nio.file.Path? = Paths.get(System.getProperty("user.dir")).toAbsolutePath()
        var fixtureDir: java.nio.file.Path? = null
        while (cursor != null) {
            val candidate = cursor.resolve("octi-web").resolve("src").resolve("crypto").resolve("__fixtures__")
            if (candidate.exists()) {
                fixtureDir = candidate
                break
            }
            cursor = cursor.parent
        }
        checkNotNull(fixtureDir) {
            "Could not locate octi-web/src/crypto/__fixtures__ walking up from ${System.getProperty("user.dir")}; create the dir first"
        }
        val outPath = fixtureDir.resolve("streaming-vectors.json")
        outPath.writeText(fixture)
        println("Wrote streaming Tink fixture to $outPath")
    }

    private fun escape(s: String): String = s.replace("\\", "\\\\").replace("\"", "\\\"")
}
