name: Code tests & eval

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-foss:
    name: Test FOSS flavor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build FOSS variant
        run: ./gradlew assembleFossDebug
      - name: Test FOSS variant
        run: ./gradlew testFossDebugUnitTest

  test-gplay:
    name: Test Google Play flavor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Google Play variant
        run: ./gradlew assembleGplayDebug
      - name: Test Google Play variant
        run: ./gradlew testGplayDebugUnitTest
